const $ = (sel, root=document) => root.querySelector(sel);
const $$ = (sel, root=document) => [...root.querySelectorAll(sel)];
const icon = (name, cls='') => `<svg class="icon ${cls}" aria-hidden="true"><use href="#i-${name}"></use></svg>`;

const state = {
  role: null,
  page: 'login',
  selectedIds: new Set(),
  expandedCandidate: 'c1',
  expandedApplication: 'a1',
  drawer: null,
  modal: null,
  toast: null,
  candidates: [
    {id:'c1',name:'Nguyễn Văn A',email:'nguyenvana@gmail.com',dob:'12/05/1996',gender:'Nam',phone:'0901 234 567',note:'Ưu tiên',active:true, address:'123 Lê Lợi, P. Bến Nghé, Q.1, TP. Hồ Chí Minh', submissions:[
      {id:'s1',date:'20/05/2025 10:30',status:'NEW',note:'Ứng viên mới nộp hồ sơ.'},
      {id:'s2',date:'19/05/2025 14:22',status:'READ',note:'Đã đọc hồ sơ, chờ sàng lọc.'},
      {id:'s3',date:'18/05/2025 09:15',status:'PROCESSED',note:'Đã liên hệ, mời phỏng vấn vòng 1.'}
    ]},
    {id:'c2',name:'Trần Thị B',email:'tranthib@gmail.com',dob:'03/08/1997',gender:'Nữ',phone:'0902 345 678',note:'',active:true, submissions:[{id:'s4',date:'30/08/2025 11:15',status:'NEW',note:''}]},
    {id:'c3',name:'Lê Văn C',email:'levanc@gmail.com',dob:'25/11/1995',gender:'Nam',phone:'0903 456 789',note:'',active:true, submissions:[{id:'s5',date:'28/08/2025 08:50',status:'PROCESSED',note:'Đang xếp lịch'}]},
    {id:'c4',name:'Phạm Thị D',email:'phamthid@gmail.com',dob:'14/02/1998',gender:'Nữ',phone:'0904 567 890',note:'',active:true, submissions:[{id:'s6',date:'26/08/2025 13:20',status:'DONE',note:'Hoàn thành'}]},
    {id:'c5',name:'Hoàng Minh E',email:'hoangminhe@gmail.com',dob:'07/07/1996',gender:'Nam',phone:'0905 678 901',note:'',active:true, submissions:[{id:'s7',date:'22/08/2025 09:10',status:'READ',note:''}]},
    {id:'c6',name:'Đỗ Thị F',email:'dothif@gmail.com',dob:'19/09/1997',gender:'Nữ',phone:'0906 789 012',note:'Tiềm năng',active:true, submissions:[{id:'s8',date:'20/08/2025 16:45',status:'NEW',note:''}]},
    {id:'c7',name:'Bùi Văn G',email:'buivang@gmail.com',dob:'28/03/1994',gender:'Nam',phone:'0907 890 123',note:'',active:true, submissions:[{id:'s9',date:'18/08/2025 15:05',status:'CLOSED',note:'Không phù hợp'}]},
    {id:'c8',name:'Nguyễn Thị H',email:'nguyenthih@gmail.com',dob:'22/12/1996',gender:'Nữ',phone:'0908 901 234',note:'Không phản hồi',active:false, submissions:[{id:'s10',date:'16/08/2025 11:05',status:'READ',note:''}]}
  ],
  applications: [
    {id:'a1',submissionId:'s1',candidateId:'c1',unit:'Khoa Kỹ thuật',team:'Điện tử – Viễn thông',position:'Giảng viên Điện tử – Viễn thông',hr:'Nguyễn Thị An',status:'FOLLOW_UP', rounds:[
      {id:'r11',no:1,topic:'Thiết kế và mô phỏng mạch số',date:'15/05/2025',start:'09:00',end:'10:00',format:'Trực tiếp',location:'Phòng Kỹ thuật 201 – EIU',status:'SCHEDULED',note:'Chuẩn bị slide bài giảng',participants:['u1','u2','u3'],active:true},
      {id:'r12',no:2,topic:'',date:'20/05/2025',start:'14:00',end:'15:30',format:'Trực tiếp',location:'Phòng 11.101.B5',status:'AWAITING',note:'',participants:['u1','u2','u3'],active:true}
    ]},
    {id:'a2',submissionId:'s4',candidateId:'c2',unit:'Khoa Kinh tế',team:'Kinh tế',position:'Giảng viên Kinh tế',hr:'Nguyễn Thị An',status:'REPORT_SUBMITTED',rounds:[{id:'r21',no:1,topic:'Phân tích dữ liệu kinh tế',date:'18/05/2025',start:'14:00',end:'15:00',format:'Trực tiếp',location:'Phòng B.201',status:'CONFIRMED',note:'',participants:['u1','u4'],active:true}]},
    {id:'a3',submissionId:'s5',candidateId:'c3',unit:'Khoa Công nghệ thông tin',team:'Công nghệ thông tin',position:'Giảng viên Công nghệ thông tin',hr:'Nguyễn Thị An',status:'WAITING_FOR_REPORT',rounds:[{id:'r31',no:1,topic:'',date:'02/06/2025',start:'09:00',end:'10:00',format:'Online',location:'Google Meet',status:'AVAILABLE',note:'',participants:['u2','u3','u4'],active:true}]},
    {id:'a4',submissionId:'s6',candidateId:'c4',unit:'Khoa Khoa học xã hội',team:'Tổ Tiếng Anh',position:'Giảng viên Ngôn ngữ Anh',hr:'Nguyễn Thị An',status:'REJECTED',rounds:[{id:'r41',no:1,topic:'Giới thiệu về phương pháp giảng dạy giao tiếp',date:'10/06/2025',start:'09:00',end:'10:00',format:'Trực tiếp',location:'Phòng A.301',status:'CANCELLED',note:'Ứng viên xin dời lịch',participants:['u1','u2'],active:true}]},
    {id:'a5',submissionId:'s7',candidateId:'c5',unit:'Khoa Kinh tế',team:'Quản trị kinh doanh',position:'Giảng viên Quản trị kinh doanh',hr:'Nguyễn Thị An',status:'AWAITING_INTERVIEW',rounds:[{id:'r51',no:1,topic:'',date:'25/05/2025',start:'09:00',end:'10:00',format:'Trực tiếp',location:'Phòng B.203',status:'AWAITING',note:'',participants:['u2','u3','u4'],active:true},{id:'r52',no:2,topic:'',date:'01/06/2025',start:'09:00',end:'10:00',format:'Trực tiếp',location:'Phòng B.203',status:'AWAITING',note:'',participants:['u2','u3','u4'],active:true}]}
  ],
  users: {
    u1:{name:'TS. Trần Minh Khoa',title:'Trưởng khoa CNTT',active:true},
    u2:{name:'ThS. Lê Hoàng Nam',title:'Giảng viên',active:true},
    u3:{name:'ThS. Phạm Quỳnh Anh',title:'Giảng viên',active:true},
    u4:{name:'ThS. Trần Thu Hương',title:'Phó Trưởng khoa CNTT',active:true}
  },
  reports: {
    r11:{u1:{knowledge:'Đáp ứng tốt yêu cầu vị trí, nắm vững kiến thức chuyên môn.',skills:'Kỹ năng phân tích và giải quyết vấn đề tốt, giao tiếp rõ ràng.',qualities:'Chủ động, trách nhiệm, tinh thần học hỏi cao.',strengths:'Điểm mạnh: tư duy logic, khả năng tự học tốt. Hạn chế: cần cải thiện kỹ năng trình bày.',other:'Ứng viên phù hợp với định hướng phát triển của khoa.',conclusion:'Đề xuất tuyển dụng.',job:'Giảng dạy các học phần chuyên ngành, tham gia nghiên cứu khoa học.',time:'Tháng 06/2025',updatedAt:'24/05/2025 14:20'},u2:{knowledge:'Kiến thức phù hợp.',skills:'Khá tốt.',qualities:'Nghiêm túc.',strengths:'Có nền tảng tốt.',other:'',conclusion:'',job:'',time:'',updatedAt:'24/05/2025 13:20'}},
    r12:{u1:{knowledge:'',skills:'',qualities:'',strengths:'',other:'',conclusion:'',job:'',time:'',updatedAt:''}},
    r21:{u1:{knowledge:'Nắm chắc chuyên môn.',skills:'Giao tiếp tốt.',qualities:'Chủ động.',strengths:'Kinh nghiệm thực tế.',other:'',conclusion:'Đề xuất tuyển.',job:'Giảng dạy và nghiên cứu.',time:'Tháng 06/2025',updatedAt:'18/05/2025 16:30'},u4:{knowledge:'Phù hợp.',skills:'Tốt.',qualities:'Tốt.',strengths:'Có kinh nghiệm.',other:'',conclusion:'',job:'',time:'',updatedAt:'18/05/2025 16:10'}},
    r41:{u1:{knowledge:'',skills:'',qualities:'',strengths:'',other:'',conclusion:'Không tiếp tục.',job:'',time:'',updatedAt:'10/06/2025 11:20'}}
  },
  currentInterviewer: 'u1'
};

const statusLabel = {
  NEW:'Mới',READ:'Đã đọc',PROCESSED:'Đang xử lý',DONE:'Hoàn thành',CLOSED:'Từ chối',INACTIVE:'Inactive',
  AVAILABLE:'Sẵn sàng',SCHEDULED:'Đã xếp lịch',AWAITING:'Chờ xác nhận',CONFIRMED:'Đã xác nhận',CANCELLED:'Hủy',
  INTERVIEW_SCHEDULING:'Chờ xếp lịch',AWAITING_INTERVIEW:'Chờ phỏng vấn',WAITING_FOR_REPORT:'Chờ báo report',REPORT_SUBMITTED:'Đã gửi Báo cáo',FOLLOW_UP:'Theo dõi thêm',ON_HOLD:'Hoãn',HIRED:'Tuyển dụng',REJECTED:'Từ chối'
};
const statusClass = s => ({NEW:'s-new',READ:'s-read',PROCESSED:'s-processed',DONE:'s-submitted',CLOSED:'s-closed',INACTIVE:'s-inactive',AVAILABLE:'s-available',SCHEDULED:'s-scheduled',AWAITING:'s-awaiting',CONFIRMED:'s-confirmed',CANCELLED:'s-cancelled',INTERVIEW_SCHEDULING:'s-available',AWAITING_INTERVIEW:'s-scheduled',WAITING_FOR_REPORT:'s-waiting',REPORT_SUBMITTED:'s-submitted',FOLLOW_UP:'s-follow',ON_HOLD:'s-awaiting',HIRED:'s-hired',REJECTED:'s-rejected'}[s]||'s-read');
const badge = s => `<span class="status ${statusClass(s)}">${statusLabel[s]||s}</span>`;
const candidate = id => state.candidates.find(x=>x.id===id);
const appById = id => state.applications.find(x=>x.id===id);
const roundById = id => state.applications.flatMap(a=>a.rounds.map(r=>({...r,application:a}))).find(x=>x.id===id);
const currentRound = a => [...a.rounds].filter(r=>r.active).sort((x,y)=>y.no-x.no)[0];
const reportCurrentSource = rid => {
  const rs=state.reports[rid]||{}; const arr=Object.entries(rs).filter(([_,r])=>r.conclusion||r.job||r.time);
  arr.sort((a,b)=>(b[1].decisionUpdatedAt||b[1].updatedAt||'').localeCompare(a[1].decisionUpdatedAt||a[1].updatedAt||'')); return arr[0];
};

function setRole(role){state.role=role; state.page = role==='candidate'?'candidate-applications':role==='interviewer'?'interviewer-report':'applications'; state.drawer=null; state.modal=null; render();}
function nav(page){state.page=page;state.drawer=null;state.modal=null;state.selectedIds.clear();render();}
function toast(msg){state.toast=msg;renderPortal();setTimeout(()=>{state.toast=null;renderPortal()},2300)}
function openDrawer(type,id){state.drawer={type,id};renderPortal()}
function closeDrawer(){state.drawer=null;renderPortal()}
function openModal(type,data={}){state.modal={type,data};renderPortal()}
function closeModal(){state.modal=null;renderPortal()}

function loginPage(){return `<div class="login-page">
  <div class="login-visual" aria-label="EIU campus"></div>
  <main class="login-panel"><section class="login-card">
    <h1>ĐĂNG NHẬP HỆ THỐNG</h1><div class="login-sub">EIU Recruitment System</div>
    <div class="login-section-title">NHÂN SỰ EIU</div>
    <button class="google-btn" onclick="openModal('rolePicker')"><span class="gmark">G</span>Đăng nhập với Google</button>
    <div class="login-note">Chỉ tài khoản đã được phê duyệt @eiu.edu.vn mới có thể đăng nhập.</div>
    <div class="separator">hoặc</div>
    <div class="login-section-title">ỨNG VIÊN</div>
    <div class="field"><label>Email của bạn</label><div class="otp-row"><input id="candidateEmail" class="input" value="candidate@gmail.com"/><button class="otp-btn" onclick="setRole('candidate')">Gửi mã đăng nhập</button></div></div>
    <div class="login-note">Prototype: nút trên đăng nhập trực tiếp để kiểm thử luồng ứng viên.</div>
    <div class="login-footer">Cần hỗ trợ? recruitment@eiu.edu.vn<br/>© 2026 Eastern International University</div>
  </section></main><div class="prototype-tag">Clickable prototype v1.0</div></div>`}

const navConfig = {
  admin:[['Tổng quan',[['home','Dashboard','dashboard'],['report','Báo cáo & Thống kê','dashboard']]],['Quản lý tuyển dụng',[['file','Phiếu ứng tuyển','applications'],['users','Vị trí tuyển dụng','placeholder'],['list','Phòng / Ban','placeholder'],['users','Nguồn ứng viên','placeholder']]],['Quản lý quy trình',[['calendar','Interview','interview'],['report','Báo cáo phỏng vấn','hr-report']]],['Quản trị hệ thống',[['list','Danh mục','placeholder'],['users','Người dùng & Phân quyền','permissions'],['settings','Cài đặt hệ thống','placeholder']]]],
  hr:[['Tổng quan',[['home','Dashboard','dashboard']]],['Quản lý tuyển dụng',[['file','Phiếu ứng tuyển','applications']]],['Quản lý quy trình',[['calendar','Interview','interview'],['report','Báo cáo phỏng vấn','hr-report']]],['Quản trị',[['list','Danh mục','placeholder']]]],
  interviewer:[['Trang chủ',[['home','Dashboard','dashboard']]],['Phỏng vấn của tôi',[['report','Báo cáo phỏng vấn','interviewer-report']]],['Tài liệu',[['file','Tài liệu','placeholder']]],['Cài đặt',[['settings','Cài đặt','placeholder']]]]
};
function sidebar(){const role=state.role;const name=role==='interviewer'?'Nguyễn Thị An':'Nguyễn Thị An';const title=role==='admin'?'Root Admin':role==='hr'?'HR Specialist':'Interviewer';return `<aside class="sidebar">
  <div class="brand"><div class="brand-logo"><span class="brand-mark"><i></i><i></i><i></i><i></i></span><span>EIU</span></div><div class="brand-name">EIU Recruitment System</div></div>
  <div class="nav-scroll">${(navConfig[role]||[]).map(g=>`<div class="nav-group"><div class="nav-label">${g[0]}</div>${g[1].map(i=>`<button class="nav-item ${state.page===i[2]?'active':''}" onclick="nav('${i[2]}')">${icon(i[0])}<span>${i[1]}</span></button>`).join('')}</div>`).join('')}</div>
  <div class="sidebar-user"><div class="avatar">NT</div><div style="flex:1"><strong>${name}</strong><span>${title}</span></div>${icon('chevron')}</div>
</aside>`}
function topbar(title,sub=''){return `<header class="topbar"><div class="page-heading"><button class="hamb">☰</button><div class="title-wrap"><h1>${title}</h1><p>${sub}</p></div></div><div class="top-actions"><button class="circle-btn" title="Thông báo">${icon('info')}</button><button class="circle-btn" title="Trợ giúp">?</button><div class="role-chip"><div class="avatar">${state.role==='admin'?'AD':'HR'}</div><div><b>${state.role==='admin'?'Root Admin':'Nguyễn Thị An'}</b><span>${state.role==='interviewer'?'Interviewer':state.role==='hr'?'HR Specialist':'Administrator'}</span></div></div><button class="btn ghost" onclick="state.role=null;state.page='login';render()">${icon('logout')} Đăng xuất</button></div></header>`}
function shell(content,title,sub=''){return `<div class="shell">${sidebar()}<main class="main">${topbar(title,sub)}${content}</main><div class="prototype-tag">Prototype • không lưu backend</div></div>`}
function pager(count=48){return `<div class="pagination"><span>Hiển thị 1 đến ${Math.min(10,count)} của ${count} kết quả</span><div class="pages"><button class="pagebtn">‹</button><button class="pagebtn active">1</button><button class="pagebtn">2</button><button class="pagebtn">3</button><button class="pagebtn">›</button></div><select class="filter-select"><option>10 / trang</option></select></div>`}

function applicationsPage(){const rows=state.candidates.map(c=>`<tr>
<td><input class="check" type="checkbox" ${state.selectedIds.has(c.id)?'checked':''} onchange="toggleSelect('${c.id}',this.checked)"></td>
<td><button class="row-btn" onclick="toggleCandidate('${c.id}')">${state.expandedCandidate===c.id?'⌃':'›'}</button></td>
<td class="name-cell" onclick="openDrawer('candidate','${c.id}')"><strong>${c.name}</strong></td><td>${c.email}</td><td>${c.dob}</td><td>${c.gender}</td><td>${c.phone}</td><td>${badge(c.status)}</td><td>${c.note||'–'}</td><td><button class="row-btn" onclick="openDrawer('candidate','${c.id}')">${icon('eye')}</button></td></tr>
${state.expandedCandidate===c.id?`<tr class="expand-row"><td colspan="10"><div class="nested"><table><thead><tr><th>Ngày ứng tuyển</th><th>Status</th><th>HR Note</th></tr></thead><tbody>${c.submissions.map(s=>`<tr onclick="openDrawer('submission','${c.id}|${s.id}')"><td>${s.date}</td><td>${badge(s.status)}</td><td>${s.note||'–'}</td></tr>`).join('')}</tbody></table></div></td></tr>`:''}`).join('');
return shell(`<div class="content"><div class="toolbar"><div class="toolbar-left"><button class="btn primary" onclick="openModal('assignApplication')">${icon('plus')} Ứng tuyển</button><button class="btn danger" ${state.selectedIds.size?'':'disabled'}>${icon('trash')} Xóa</button><button class="btn" onclick="bulkStatus()">Status ${icon('chevron')}</button><button class="btn" onclick="toggleInactive()">Inactive</button><button class="btn">${icon('mail')} Gửi thư ứng viên</button></div><div class="toolbar-right"><div class="searchbox"><input class="input" placeholder="Tìm kiếm...">${icon('search')}</div><button class="btn">${icon('filter')} Bộ lọc</button></div></div>
<div class="table-card"><table><thead><tr><th style="width:34px"></th><th style="width:28px"></th><th>Tên</th><th>Email</th><th>Ngày sinh</th><th>Giới tính</th><th>SĐT</th><th>Trạng thái</th><th>HR Note</th><th></th></tr></thead><tbody>${rows}</tbody></table>${pager(240)}</div></div>`,'Quản lý phiếu ứng tuyển','Quản lý tất cả phiếu ứng tuyển và trạng thái xử lý.');}
function toggleCandidate(id){state.expandedCandidate=state.expandedCandidate===id?null:id;render()}
function toggleSelect(id,on){on?state.selectedIds.add(id):state.selectedIds.delete(id);render()}
function bulkStatus(){if(!state.selectedIds.size)return toast('Chọn ít nhất một ứng viên trước.');openModal('bulkStatus')}
function toggleInactive(){if(!state.selectedIds.size)return toast('Chọn ít nhất một ứng viên trước.');state.selectedIds.forEach(id=>{let c=candidate(id);if(c)c.active=!c.active});toast('Đã cập nhật trạng thái Active/Inactive; Submission status được giữ nguyên.');render()}

function interviewPage(){const rows=state.applications.map(a=>{const c=candidate(a.candidateId),cr=currentRound(a),open=state.expandedApplication===a.id;return `<tr><td><button class="row-btn" onclick="toggleApp('${a.id}')">${open?'⌃':'›'}</button></td><td class="name-cell"><strong>${c.name}</strong><span>${a.position} - ${a.unit}</span></td><td>${a.position}</td><td>${a.rounds.filter(r=>r.active).length} vòng</td><td>${a.rounds[0].date} – ${cr.date}</td><td>${badge(cr.status)}</td><td>${icon('users')} ${cr.participants.length}</td><td>${cr.note||'–'}</td><td><button class="row-btn" onclick="openDrawer('round','${cr.id}')">${icon('eye')}</button></td></tr>
${open?`<tr class="expand-row"><td colspan="9"><div class="nested"><table><thead><tr><th>Vòng</th><th>Thời gian</th><th>Status</th><th>Người tham dự</th><th>HR Note</th><th></th></tr></thead><tbody>${a.rounds.map(r=>`<tr><td class="strong">Vòng ${r.no}<div class="small muted">${r.topic||'Chưa nhập Demo Topic'}</div></td><td>${r.date}<br>${r.start} – ${r.end}</td><td>${badge(r.status)}</td><td>${icon('users')} ${r.participants.length}</td><td>${r.note||'–'}</td><td><button class="row-btn" onclick="openDrawer('round','${r.id}')">${icon('eye')}</button></td></tr>`).join('')}</tbody></table></div></td></tr>`:''}`}).join('');
return shell(`<div class="content"><div class="toolbar"><div class="toolbar-left"><button class="btn primary" onclick="openModal('createRound')">${icon('plus')} Tạo lịch</button><button class="btn" onclick="copyLatest()">${icon('copy')} Sao chép lịch</button><button class="btn danger">${icon('trash')} Xóa</button><button class="btn">Status ${icon('chevron')}</button><button class="btn">${icon('mail')} Gửi thư ứng viên</button><button class="btn">${icon('mail')} Gửi thư người tham dự</button></div><div class="toolbar-right"><div class="searchbox"><input class="input" placeholder="Tìm kiếm...">${icon('search')}</div><button class="btn">${icon('filter')} Bộ lọc</button></div></div>
<div class="table-card"><table><thead><tr><th></th><th>Ứng viên</th><th>Vị trí ứng tuyển</th><th>Vòng</th><th>Thời gian phỏng vấn</th><th>Trạng thái</th><th>Người tham dự</th><th>HR Note</th><th></th></tr></thead><tbody>${rows}</tbody></table>${pager(68)}</div></div>`,'Interview','Quản lý lịch phỏng vấn và người tham dự');}
function toggleApp(id){state.expandedApplication=state.expandedApplication===id?null:id;render()}
function copyLatest(){const a=appById(state.expandedApplication||'a1');const r=currentRound(a);openModal('copyRound',{appId:a.id,roundId:r.id})}

function hrReportPage(){const rows=state.applications.map(a=>{const c=candidate(a.candidateId),r=currentRound(a);return `<tr><td><input class="check" type="checkbox"></td><td class="name-cell"><strong>${c.name}</strong></td><td>${a.position}</td><td>Vòng ${r.no}</td><td>${r.date}</td><td>${badge(a.status)}</td><td>–</td><td><button class="row-btn" onclick="openDrawer('hrReport','${a.id}')">${icon('eye')}</button></td></tr>`}).join('');
return shell(`<div class="content"><div class="toolbar"><div class="toolbar-left"><button class="btn danger">${icon('trash')} Xóa</button><button class="btn">Trạng thái ${icon('chevron')}</button><button class="btn">${icon('eye')} Ẩn khỏi Interviewer / Hiện cho Interviewer</button><button class="btn">${icon('eye')} Xem PDF</button><button class="btn">${icon('download')} Tải PDF</button></div><div class="toolbar-right"><div class="searchbox"><input class="input" placeholder="Tìm kiếm theo họ tên, vị trí...">${icon('search')}</div><select class="filter-select"><option>Vị trí ứng tuyển</option></select><select class="filter-select"><option>Trạng thái</option></select></div></div>
<div class="table-card"><table><thead><tr><th></th><th>Họ và tên</th><th>Vị trí</th><th>Vòng cuối cùng</th><th>Ngày phỏng vấn</th><th>Trạng thái</th><th>Ghi chú</th><th></th></tr></thead><tbody>${rows}</tbody></table>${pager(48)}</div></div>`,'Báo cáo phỏng vấn (HR)','Xem báo cáo phỏng vấn và quyết định.');}

function interviewerPage(){const apps=state.applications.filter(a=>currentRound(a).participants.includes(state.currentInterviewer));const rows=apps.map(a=>{const c=candidate(a.candidateId),r=currentRound(a),own=state.reports[r.id]?.[state.currentInterviewer];return `<tr><td class="name-cell"><strong>${c.name}</strong><span>${c.email}</span></td><td>${a.position}</td><td>Vòng ${r.no}</td><td>${r.date}<br>${r.start} – ${r.end}</td><td>${badge(a.status)}</td><td><button class="row-btn" onclick="openDrawer('interviewer','${a.id}')">${icon('eye')}</button>${own?`<button class="row-btn" onclick="openDrawer('interviewer','${a.id}')">${icon('edit')}</button>`:''}</td></tr>`}).join('');
return shell(`<div class="content"><div class="toolbar"><div class="toolbar-left"><button class="btn">Đặt lại bộ lọc</button></div><div class="toolbar-right"><div class="searchbox"><input class="input" placeholder="Tìm kiếm theo họ tên, vị trí...">${icon('search')}</div><select class="filter-select"><option>Vị trí: Tất cả</option></select><select class="filter-select"><option>Vòng: Tất cả</option></select><select class="filter-select"><option>Trạng thái: Tất cả</option></select><button class="btn primary">Lọc</button></div></div>
<div class="table-card"><table><thead><tr><th>Họ và tên</th><th>Vị trí</th><th>Vòng</th><th>Ngày phỏng vấn</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${rows}</tbody></table>${pager(apps.length)}</div></div>`,'Báo cáo phỏng vấn của tôi','Nhập báo cáo đánh giá ứng viên sau mỗi buổi phỏng vấn.');}

function candidateApplications(){const submissions=[{id:1,date:'24/05/2025 10:32',status:'NEW'},{id:2,date:'22/05/2025 14:18',status:'PROCESSED'},{id:3,date:'20/05/2025 09:05',status:'DONE'}];return `<div class="candidate-shell">${candidateSidebar()}<main class="candidate-content"><div class="candidate-head"><div><h1>Phiếu ứng tuyển</h1><div class="muted small">Quản lý các phiếu ứng tuyển của bạn</div></div><div class="top-actions"><button class="circle-btn">?</button><div class="role-chip"><div class="avatar">NT</div><div><b>Nguyễn Thị An</b><span>Ứng viên</span></div></div><button class="btn ghost" onclick="state.role=null;state.page='login';render()">${icon('logout')} Đăng xuất</button></div></div><div class="candidate-actions"><button class="btn" onclick="nav('candidate-form')">${icon('plus')} Tạo phiếu mới</button><button class="btn primary">${icon('file')} Phiếu của tôi</button></div><div class="candidate-card"><table><thead><tr><th>STT</th><th>Time stamp</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${submissions.map((s,i)=>`<tr><td>${i+1}</td><td>${s.date}</td><td>${badge(s.status)}</td><td>${s.status==='NEW'?`<button class="row-btn" onclick="nav('candidate-form')">${icon('edit')}</button>`:''}<button class="row-btn" onclick="openDrawer('candidateOwn','c1')">${icon('eye')}</button></td></tr>`).join('')}</tbody></table>${pager(3)}</div></main><div class="prototype-tag">Candidate portal</div></div>`}
function candidateSidebar(){return `<aside class="sidebar"><div class="brand"><div class="brand-logo"><span class="brand-mark"><i></i><i></i><i></i><i></i></span><span>EIU</span></div><div class="brand-name">EIU Recruitment System</div></div><div class="nav-scroll"><div class="nav-group"><div class="nav-label">Ứng viên</div><button class="nav-item">${icon('home')} Trang chủ</button><button class="nav-item active">${icon('file')} Phiếu ứng tuyển</button><button class="nav-item">${icon('person')} Hồ sơ cá nhân</button></div></div><div class="sidebar-user"><div class="avatar">NT</div><div><strong>Nguyễn Thị An</strong><span>Ứng viên</span></div></div></aside>`}
function candidateForm(){return `<div class="candidate-shell">${candidateSidebar()}<main class="candidate-content"><div class="candidate-head"><div><h1>Đăng ký mới</h1><div class="muted small">Hoàn tất một phiếu trên cùng một trang.</div></div><button class="btn" onclick="nav('candidate-applications')">← Phiếu của tôi</button></div>
<form onsubmit="event.preventDefault();toast('Đã gửi phiếu ứng tuyển mẫu');nav('candidate-applications')">
<div class="form-section"><h3>01 · THÔNG TIN CHUNG / GENERAL INFORMATION</h3><div class="form-grid"><div class="field"><label>Họ tên *</label><input class="input" value="Nguyễn Thị An" required></div><div class="field"><label>Email</label><input class="input" value="candidate@gmail.com" disabled></div><div class="field"><label>Ngày sinh *</label><input class="input" type="date" value="1995-08-15"></div><div class="field"><label>Giới tính *</label><select class="select"><option>Nữ</option><option>Nam</option></select></div><div class="field"><label>Số điện thoại *</label><input class="input" value="0901 234 567"></div><div class="field"><label>Địa chỉ hiện tại *</label><input class="input" value="TP. Hồ Chí Minh"></div></div></div>
<div class="form-section"><h3>02 · QUÁ TRÌNH HỌC TẬP / EDUCATION</h3><div class="repeat-item"><div class="form-grid"><div class="field"><label>Thời gian *</label><input class="input" value="2018 – 2022"></div><div class="field"><label>Học vấn *</label><select class="select"><option>Cử nhân</option><option>Thạc sĩ</option></select></div><div class="field"><label>Chuyên ngành *</label><input class="input" value="Quản trị kinh doanh"></div><div class="field"><label>Trường *</label><input class="input" value="Eastern International University"></div></div></div><button type="button" class="btn">${icon('plus')} Thêm quá trình học tập</button></div>
<div class="form-section"><h3>03 · HỒ SƠ ĐÍNH KÈM</h3><div class="field"><label>CV *</label><input class="input" type="file"></div><div class="form-grid" style="margin-top:12px"><div class="field"><label>Bằng cấp</label><input class="input" type="file"></div><div class="field"><label>Bảng điểm</label><input class="input" type="file"></div></div></div>
<div class="form-section"><label style="font-size:12px"><input type="checkbox" checked> Tôi xác nhận thông tin trên là chính xác và đồng ý với chính sách tuyển dụng.</label></div><div style="display:flex;justify-content:flex-end;gap:8px"><button type="button" class="btn" onclick="nav('candidate-applications')">Hủy</button><button class="btn primary" type="submit">Gửi phiếu</button></div></form></main></div>`}

function placeholder(){return shell(`<div class="content"><div class="table-card" style="padding:50px;text-align:center"><h3 style="color:#164575">Trang đang ngoài phạm vi prototype UX-UAT vòng 1</h3><p class="muted">Dùng menu Phiếu ứng tuyển, Interview, Báo cáo phỏng vấn hoặc Người dùng & Phân quyền.</p></div></div>`,'Trang mẫu','Placeholder cho prototype');}
function dashboard(){return shell(`<div class="content"><div class="table-card" style="padding:36px"><h3 style="color:#164575">Prototype Dashboard</h3><p class="muted">Dashboard/KPI sẽ thiết kế sau. Vòng UX-UAT hiện tập trung vào intake → interview → report.</p><div style="display:flex;gap:10px;margin-top:20px"><button class="btn primary" onclick="nav('applications')">Đi tới Phiếu ứng tuyển</button><button class="btn" onclick="nav('interview')">Đi tới Interview</button></div></div></div>`,'Dashboard','Tổng quan tuyển dụng');}
function permissionsPage(){return shell(`<div class="content"><div class="toolbar"><div class="toolbar-left"><button class="btn primary">${icon('plus')} Thêm người dùng</button><button class="btn">Phân quyền HR</button></div></div><div class="table-card"><table><thead><tr><th>Người dùng</th><th>Email</th><th>Role</th><th>Trạng thái</th><th>Quyền HR</th></tr></thead><tbody><tr><td class="strong">Root Admin</td><td>root.admin@eiu.edu.vn</td><td>Admin</td><td>${badge('CONFIRMED')}</td><td>Tất cả quyền · duy nhất 01 Root Admin</td></tr><tr><td>Nguyễn Thị An</td><td>an.nt@eiu.edu.vn</td><td>Chuyên viên HR</td><td>${badge('CONFIRMED')}</td><td>Phiếu, Interview, Báo cáo, Sửa report Interviewer</td></tr><tr><td>TS. Trần Minh Khoa</td><td>khoa.tm@eiu.edu.vn</td><td>Interviewer</td><td>${badge('CONFIRMED')}</td><td>Báo cáo của các lịch được phân công</td></tr></tbody></table></div></div>`,'Người dùng & Phân quyền','Root Admin phân từng quyền cho HR.');}

function render(){const app=$('#app');if(!state.role||state.page==='login')app.innerHTML=loginPage();else if(state.role==='candidate')app.innerHTML=state.page==='candidate-form'?candidateForm():candidateApplications();else {const pages={applications:applicationsPage,interview:interviewPage,'hr-report':hrReportPage,'interviewer-report':interviewerPage,permissions:permissionsPage,dashboard,placeholder};app.innerHTML=(pages[state.page]||placeholder)()}renderPortal()}

function renderPortal(){const p=$('#portal');let html='';if(state.drawer)html+=drawerHtml();if(state.modal)html+=modalHtml();if(state.toast)html+=`<div class="toast">${state.toast}</div>`;p.innerHTML=html}

function drawerHtml(){const d=state.drawer;if(d.type==='candidate'||d.type==='submission')return candidateDrawer(d);if(d.type==='round')return roundDrawer(d.id);if(d.type==='hrReport')return hrReportDrawer(d.id);if(d.type==='interviewer')return interviewerDrawer(d.id);if(d.type==='candidateOwn')return candidateOwnDrawer();return ''}
function closeBtn(){return `<button class="row-btn" onclick="closeDrawer()" aria-label="Đóng">${icon('close')}</button>`}
function candidateDrawer(d){const cid=d.type==='candidate'?d.id:d.id.split('|')[0],c=candidate(cid);return `<div class="backdrop" onclick="closeDrawer()"></div><aside class="drawer narrow"><div class="drawer-head"><div class="drawer-title-row"><div><h2>Chi tiết phiếu ứng tuyển</h2><div class="drawer-sub">Thông tin chi tiết về phiếu ứng tuyển đã chọn.</div></div>${closeBtn()}</div><div class="drawer-actions"><button class="btn">${icon('edit')} Edit</button><button class="btn danger">${icon('trash')} Xóa</button><button class="btn">${icon('eye')} Preview</button></div></div><div class="drawer-body"><div class="section"><div class="section-title">Thông tin ứng tuyển</div><dl class="kv"><dt>Ứng viên</dt><dd>${c.name}</dd><dt>Email</dt><dd>${c.email}</dd><dt>Ngày sinh</dt><dd>${c.dob}</dd><dt>Giới tính</dt><dd>${c.gender}</dd><dt>SĐT</dt><dd>${c.phone}</dd><dt>Địa chỉ</dt><dd>${c.address||'TP. Hồ Chí Minh'}</dd><dt>Trạng thái</dt><dd>${badge(c.status)}</dd></dl></div><div class="section"><div class="section-title">HR Note</div><div class="note-box">${c.note||'Chưa có ghi chú.'}</div></div><div class="section"><div class="section-title">Thông tin tuyển dụng</div><dl class="kv"><dt>Khoa/Phòng</dt><dd>Khoa Kỹ thuật</dd><dt>Ngành/Tổ</dt><dd>Điện tử – Viễn thông</dd><dt>Vị trí</dt><dd>Giảng viên Điện tử – Viễn thông</dd></dl></div><div class="section"><div class="section-title">Tài liệu đính kèm (3)</div><div class="file-row"><span>CV_NguyenVanA.pdf</span><span>512 KB</span>${icon('download')}</div><div class="file-row"><span>BangCap.pdf</span><span>768 KB</span>${icon('download')}</div><div class="file-row"><span>DonUngTuyen.docx</span><span>45 KB</span>${icon('download')}</div></div></div></aside>`}
function roundDrawer(rid){const r=roundById(rid),a=r.application,c=candidate(a.candidateId);return `<div class="backdrop" onclick="closeDrawer()"></div><aside class="drawer narrow"><div class="drawer-head"><div class="drawer-title-row"><div><h2>Thông tin lịch phỏng vấn</h2><div class="drawer-sub">Vòng ${r.no} · ${a.position}</div></div>${closeBtn()}</div><div class="drawer-actions"><button class="btn" onclick="openModal('editRound',{roundId:'${r.id}'})">${icon('edit')} Edit</button><button class="btn" onclick="openModal('copyRound',{appId:'${a.id}',roundId:'${r.id}'})">${icon('copy')} Sao chép</button><button class="btn danger">${icon('trash')} Xóa</button><button class="btn">${icon('mail')} Gửi thư ứng viên</button><button class="btn">${icon('mail')} Gửi thư người tham dự</button></div></div><div class="drawer-body"><div class="section"><div class="section-title">Thông tin ứng viên</div><dl class="kv"><dt>Họ tên</dt><dd>${c.name}</dd><dt>Email</dt><dd>${c.email}</dd><dt>SĐT</dt><dd>${c.phone}</dd><dt>Khoa/Phòng</dt><dd>${a.unit}</dd><dt>Ngành/Tổ</dt><dd>${a.team}</dd><dt>Vị trí ứng tuyển</dt><dd>${a.position}</dd></dl></div><div class="section"><div class="section-title">Thông tin phỏng vấn</div><dl class="kv"><dt>Vòng phỏng vấn</dt><dd>Vòng ${r.no}</dd><dt>Đề giảng thử</dt><dd>${r.topic||'Chưa nhập'}</dd><dt>Thời gian</dt><dd>${r.date} · ${r.start} – ${r.end}</dd><dt>Địa điểm</dt><dd>${r.location}</dd><dt>Hình thức</dt><dd>${r.format}</dd><dt>Trạng thái</dt><dd>${badge(r.status)}</dd><dt>HR phụ trách</dt><dd>${a.hr}</dd></dl></div><div class="section"><div class="section-title">Người tham dự (${r.participants.length})</div>${r.participants.map((uid,i)=>`<div class="file-row" style="grid-template-columns:26px 1fr"><span>${i+1}.</span><span>${state.users[uid].name} (${state.users[uid].title})</span></div>`).join('')}</div><div class="section"><div class="section-title">Tài liệu phỏng vấn</div><div class="file-row"><span>Đề giảng thử – Mạch số.pdf</span><span>245 KB</span>${icon('download')}</div></div><div class="section"><div class="section-title">Lịch sử cập nhật</div><dl class="kv"><dt>Tạo bởi</dt><dd>Nguyễn Thị An · 13/05/2025 14:20</dd><dt>Cập nhật lần cuối</dt><dd>Nguyễn Thị An · 13/05/2025 14:25</dd></dl></div></div></aside>`}
function hrReportDrawer(aid){const a=appById(aid),r=currentRound(a),rs=state.reports[r.id]||{},src=reportCurrentSource(r.id);return `<div class="backdrop" onclick="closeDrawer()"></div><aside class="drawer"><div class="drawer-head"><div class="drawer-title-row"><div><h2>Báo cáo phỏng vấn</h2><div class="drawer-sub">Chỉ hiển thị dữ liệu của Page Báo cáo; vòng hiện hành: Vòng ${r.no}</div></div>${closeBtn()}</div><div class="drawer-actions"><button class="btn" onclick="openModal('hrEditReport',{appId:'${a.id}'})">${icon('edit')} Edit</button><button class="btn danger">${icon('trash')} Xóa</button><button class="btn">${icon('eye')} Ẩn khỏi Interviewer</button><button class="btn" onclick="openModal('pdf',{appId:'${a.id}'})">${icon('eye')} Xem PDF</button><button class="btn">${icon('download')} Tải PDF</button></div></div><div class="drawer-body"><div class="section"><dl class="kv"><dt>Trạng thái báo cáo</dt><dd>${badge(a.status)}</dd><dt>HR phụ trách</dt><dd>${a.hr}</dd><dt>Ghi chú</dt><dd>Ứng viên đáp ứng tốt yêu cầu vị trí.</dd><dt>Hiển thị với Interviewer</dt><dd>${badge('CONFIRMED')}</dd><dt>Nguồn kết luận hiện hành</dt><dd>${src?state.users[src[0]]?.name||src[0]:'Chưa có'}</dd><dt>Cập nhật gần nhất</dt><dd>${src?.[1]?.updatedAt||'–'}</dd></dl></div><div class="section"><div class="section-title">Báo cáo của Interviewer</div>${r.participants.map((uid,i)=>reportAccordion(r.id,uid,i)).join('')}</div><div class="section"><div class="section-title">Kết luận hiện hành</div>${src?`<div class="report-grid"><div class="label">Kết luận</div><div class="value">${src[1].conclusion||'–'}</div><div class="label">Dự kiến công việc cụ thể được phân công</div><div class="value">${src[1].job||'–'}</div><div class="label">Thời gian dự kiến tuyển dụng</div><div class="value">${src[1].time||'–'}</div></div>`:'<div class="muted small">Chưa có kết luận từ Interviewer.</div>'}</div></div></aside>`}
function reportAccordion(rid,uid,i){const u=state.users[uid],rep=state.reports[rid]?.[uid]||{};return `<div class="accordion ${i===0?'open':''}"><div class="accordion-head" onclick="this.parentElement.classList.toggle('open')"><span>Interviewer ${i+1}: ${u.name} – ${u.title}</span><span>⌄</span></div><div class="accordion-body"><div class="report-grid"><div class="label">Kiến thức chuyên môn</div><div class="value">${rep.knowledge||'...'}</div><div class="label">Kỹ năng cần thiết</div><div class="value">${rep.skills||'...'}</div><div class="label">Phẩm chất/tính cách</div><div class="value">${rep.qualities||'...'}</div><div class="label">Điểm mạnh và hạn chế</div><div class="value">${rep.strengths||'...'}</div><div class="label">Khác</div><div class="value">${rep.other||'...'}</div></div></div></div>`}
function interviewerDrawer(aid){const a=appById(aid),r=currentRound(a),c=candidate(a.candidateId),uid=state.currentInterviewer,rep=state.reports[r.id]?.[uid];const editable=!['HIRED','REJECTED'].includes(a.status);return `<div class="backdrop" onclick="closeDrawer()"></div><aside class="drawer"><div class="drawer-head"><div class="drawer-title-row"><div><h2>Chi tiết phỏng vấn & Báo cáo</h2><div class="drawer-sub">${c.name} · Vòng ${r.no}</div></div>${closeBtn()}</div><div class="drawer-actions">${editable?`<button class="btn primary" onclick="openModal('editOwnReport',{appId:'${a.id}'})">${icon(rep?'edit':'report')} ${rep?'Edit':'Báo cáo PV'}</button>`:''}<button class="btn" onclick="openModal('pdf',{appId:'${a.id}'})">${icon('eye')} Xem</button><button class="btn">${icon('download')} Tải PDF</button></div></div><div class="drawer-body"><div class="section"><div class="section-title">Thông tin phỏng vấn</div><dl class="kv"><dt>Họ tên</dt><dd>${c.name}</dd><dt>Email</dt><dd>${c.email}</dd><dt>SĐT</dt><dd>${c.phone}</dd><dt>Khoa/Phòng</dt><dd>${a.unit}</dd><dt>Ngành/Tổ</dt><dd>${a.team}</dd><dt>Vị trí</dt><dd>${a.position}</dd><dt>Đề giảng thử</dt><dd>${r.topic||'–'}</dd><dt>Thời gian</dt><dd>${r.date} · ${r.start} – ${r.end}</dd><dt>Hình thức</dt><dd>${r.format}</dd><dt>Địa điểm</dt><dd>${r.location}</dd></dl></div><div class="section"><div class="section-title">Thông tin báo cáo của tôi</div>${rep?`<div class="report-grid"><div class="label">Kiến thức chuyên môn</div><div>${rep.knowledge||'–'}</div><div class="label">Kỹ năng cần thiết</div><div>${rep.skills||'–'}</div><div class="label">Phẩm chất/tính cách</div><div>${rep.qualities||'–'}</div><div class="label">Điểm mạnh và hạn chế</div><div>${rep.strengths||'–'}</div><div class="label">Khác</div><div>${rep.other||'–'}</div><div class="label">Kết luận</div><div>${rep.conclusion||'–'}</div><div class="label">Dự kiến công việc cụ thể</div><div>${rep.job||'–'}</div><div class="label">Thời gian dự kiến tuyển dụng</div><div>${rep.time||'–'}</div></div>`:'<div class="muted small">Chưa nhập báo cáo.</div>'}</div></div></aside>`}
function candidateOwnDrawer(){return `<div class="backdrop" onclick="closeDrawer()"></div><aside class="drawer narrow"><div class="drawer-head"><div class="drawer-title-row"><div><h2>Chi tiết phiếu ứng tuyển</h2><div class="drawer-sub">Phiếu có thể chỉnh sửa khi trạng thái là Mới.</div></div>${closeBtn()}</div></div><div class="drawer-body"><div class="section"><div class="section-title">Thông tin cá nhân</div><dl class="kv"><dt>Họ tên</dt><dd>Nguyễn Thị An</dd><dt>Email</dt><dd>candidate@gmail.com</dd><dt>Ngày sinh</dt><dd>15/08/1995</dd><dt>Giới tính</dt><dd>Nữ</dd><dt>Số điện thoại</dt><dd>0901 234 567</dd></dl></div><div class="section"><div class="section-title">Hồ sơ đính kèm</div><div class="file-row"><span>CV_Nguyen_Thi_An.pdf</span><span>512 KB</span>${icon('download')}</div><div class="file-row"><span>Bang_cap_dai_hoc.jpg</span><span>842 KB</span>${icon('download')}</div></div></div><div class="drawer-footer"><button class="btn" onclick="closeDrawer()">Đóng</button><button class="btn primary" onclick="closeDrawer();nav('candidate-form')">${icon('edit')} Chỉnh sửa phiếu</button></div></aside>`}

function modalHtml(){const m=state.modal;if(m.type==='rolePicker')return rolePicker();if(m.type==='assignApplication')return assignApplicationModal();if(m.type==='bulkStatus')return bulkStatusModal();if(m.type==='createRound'||m.type==='copyRound'||m.type==='editRound')return roundModal(m);if(m.type==='editOwnReport')return reportEditModal(m.data.appId,false);if(m.type==='hrEditReport')return reportEditModal(m.data.appId,true);if(m.type==='pdf')return pdfModal(m.data.appId);return ''}
function modalFrame(title,body,footer=''){return `<div class="modal-wrap" onclick="if(event.target===this)closeModal()"><section class="modal"><div class="modal-head"><div><h3>${title}</h3></div><button class="row-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body">${body}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}</section></div>`}
function rolePicker(){return modalFrame('Prototype — chọn vai trò EIU',`<p class="muted small">Auth thật sẽ dùng Google @eiu.edu.vn. Màn hình này chỉ để UX-UAT nhanh.</p><div style="display:grid;gap:9px"><button class="btn primary" onclick="setRole('admin')">Root Admin — toàn quyền</button><button class="btn" onclick="setRole('hr')">Chuyên viên HR — quyền được Admin cấp</button><button class="btn" onclick="setRole('interviewer')">Interviewer</button></div>`)}
function assignApplicationModal(){return modalFrame('Ứng tuyển / Update Information',`<div class="form-grid"><div class="field wide"><label>Ứng viên *</label><select class="select"><option>Nguyễn Văn A — nguyenvana@gmail.com</option><option>Trần Thị B — tranthib@gmail.com</option></select><label class="small"><input type="checkbox"> Trùng</label></div><div class="field"><label>Khoa/Phòng *</label><select class="select"><option>Khoa Kỹ thuật</option><option>Khoa Kinh tế</option></select></div><div class="field"><label>Ngành/Tổ</label><select class="select"><option>Điện tử – Viễn thông</option></select></div><div class="field"><label>Vị trí *</label><select class="select"><option>Giảng viên Điện tử – Viễn thông</option></select></div><div class="field"><label>HR phụ trách *</label><select class="select"><option>Nguyễn Thị An</option></select></div></div><div class="alert">Nếu tổ hợp Candidate + Khoa/Phòng + Ngành/Tổ + Vị trí đã tồn tại, hệ thống sẽ cảnh báo và yêu cầu xác nhận trước khi cập nhật Application hiện có.</div>`,`<button class="btn" onclick="closeModal()">Hủy</button><button class="btn primary" onclick="closeModal();toast('Đã cập nhật Application mẫu')">Lưu</button>`)}
function bulkStatusModal(){return modalFrame('Đổi trạng thái',`<p class="small">Đã chọn <b>${state.selectedIds.size}</b> ứng viên. Rule prototype: thao tác all-or-nothing.</p><select class="select"><option>Mark New</option><option>Đã đọc</option></select>`,`<button class="btn" onclick="closeModal()">Hủy</button><button class="btn primary" onclick="closeModal();toast('Đã áp dụng trạng thái cho toàn bộ lựa chọn')">Xác nhận</button>`)}
function roundModal(m){let a=appById(m.data?.appId||state.expandedApplication||'a1'),src=m.data?.roundId?roundById(m.data.roundId):currentRound(a),copy=m.type==='copyRound',edit=m.type==='editRound';let no=copy?Math.max(...a.rounds.map(r=>r.no))+1:(edit?src.no:Math.max(...a.rounds.map(r=>r.no))+1);return modalFrame(copy?'Sao chép lịch phỏng vấn':edit?'Chỉnh sửa lịch phỏng vấn':'Tạo lịch phỏng vấn',`<div class="form-grid"><div class="field wide"><label>Application</label><select id="roundApp" class="select"><option value="${a.id}">${candidate(a.candidateId).name} — ${a.position}</option>${state.applications.filter(x=>x.id!==a.id).map(x=>`<option value="${x.id}">${candidate(x.candidateId).name} — ${x.position}</option>`).join('')}</select></div><div class="field"><label>Vòng</label><input id="roundNo" class="input" value="${no}" disabled></div><div class="field"><label>Demo Topic</label><input id="roundTopic" class="input" value="${copy?'':src?.topic||''}" placeholder="Tạo vòng mới mặc định để trống"></div><div class="field"><label>Ngày *</label><input id="roundDate" class="input" type="date" value="2025-06-15"></div><div class="field"><label>Giờ bắt đầu *</label><input id="roundStart" class="input" type="time" value="${copy?src.start:'09:00'}"></div><div class="field"><label>Giờ kết thúc *</label><input id="roundEnd" class="input" type="time" value="${copy?src.end:'10:00'}"></div><div class="field"><label>Hình thức</label><select class="select"><option>Trực tiếp</option><option>Online</option></select></div><div class="field"><label>Địa điểm</label><input id="roundLocation" class="input" value="${copy?src.location:'Phòng 11.101.B5'}"></div><div class="field wide"><label>Người tham dự</label><select id="roundParticipants" class="select"><option value="u1,u2,u3">TS. Trần Minh Khoa; ThS. Lê Hoàng Nam; ThS. Phạm Quỳnh Anh</option><option value="u1,u4">TS. Trần Minh Khoa; ThS. Trần Thu Hương</option></select></div></div><div id="conflictBox"></div>`,`<button class="btn" onclick="closeModal()">Hủy</button><button class="btn primary" onclick="saveRound('${m.type}','${src?.id||''}')">Xác nhận</button>`)}
function saveRound(type,srcId){const appId=$('#roundApp').value,a=appById(appId),date=$('#roundDate').value,start=$('#roundStart').value,end=$('#roundEnd').value,parts=$('#roundParticipants').value.split(',');const conflict=a.rounds.some(r=>r.active&&r.date===date&&start<r.end&&end>r.start&&r.participants.some(p=>parts.includes(p)));if(conflict){$('#conflictBox').innerHTML=`<div class="alert">Có Interviewer bị trùng thời gian phỏng vấn. Prototype chặn xác nhận theo business rule.</div>`;return}if(type==='editRound'){let r=roundById(srcId);Object.assign(r,{date,start,end,topic:$('#roundTopic').value,location:$('#roundLocation').value,participants:parts})}else{const no=Math.max(0,...a.rounds.map(r=>r.no))+1;a.rounds.push({id:'r'+Date.now(),no,topic:$('#roundTopic').value,date,start,end,format:'Trực tiếp',location:$('#roundLocation').value,status:'AVAILABLE',note:'',participants:parts,active:true})}closeModal();toast(type==='copyRound'?'Đã tạo bản sao lịch mẫu':'Đã lưu lịch phỏng vấn');render()}
function reportEditModal(aid,isHR){const a=appById(aid),r=currentRound(a),uid=state.currentInterviewer,rep=state.reports[r.id]?.[uid]||{};return modalFrame(isHR?'HR chỉnh báo cáo Interviewer':'Báo cáo phỏng vấn',`<div class="alert" style="display:${isHR?'block':'none'}">Nếu Interviewer đã cập nhật record sau khi HR mở, HR phải reload. Interviewer luôn thắng concurrency.</div><div class="report-fields"><div class="field-row"><label>Kiến thức chuyên môn</label><textarea id="repKnowledge" class="textarea">${rep.knowledge||''}</textarea></div><div class="field-row"><label>Kỹ năng cần thiết</label><textarea id="repSkills" class="textarea">${rep.skills||''}</textarea></div><div class="field-row"><label>Phẩm chất, tính cách</label><textarea id="repQualities" class="textarea">${rep.qualities||''}</textarea></div><div class="field-row"><label>Điểm mạnh và hạn chế</label><textarea id="repStrengths" class="textarea">${rep.strengths||''}</textarea></div><div class="field-row"><label>Khác</label><textarea id="repOther" class="textarea">${rep.other||''}</textarea></div><div class="field-row"><label>Kết luận</label><textarea id="repConclusion" class="textarea">${rep.conclusion||''}</textarea></div><div class="field-row"><label>Dự kiến công việc cụ thể được phân công</label><textarea id="repJob" class="textarea">${rep.job||''}</textarea></div><div class="field-row"><label>Thời gian dự kiến tuyển dụng</label><input id="repTime" class="input" value="${rep.time||''}"></div></div><p class="muted small">Không có chấm điểm. Mỗi Interviewer có một báo cáo riêng.</p>`,`<button class="btn" onclick="closeModal()">Hủy</button><button class="btn primary" onclick="saveReport('${r.id}','${uid}')">Lưu</button>`)}
function saveReport(rid,uid){state.reports[rid]=state.reports[rid]||{};state.reports[rid][uid]={knowledge:$('#repKnowledge').value,skills:$('#repSkills').value,qualities:$('#repQualities').value,strengths:$('#repStrengths').value,other:$('#repOther').value,conclusion:$('#repConclusion').value,job:$('#repJob').value,time:$('#repTime').value,updatedAt:new Date().toLocaleString('vi-VN')};closeModal();toast('Đã lưu báo cáo của Interviewer');render()}
function pdfModal(aid){const a=appById(aid),r=currentRound(a),src=reportCurrentSource(r.id);return modalFrame(`Preview Báo cáo phỏng vấn — Vòng ${r.no}`,`<div style="border:1px solid var(--line);padding:22px;background:#fff;min-height:420px"><div style="text-align:center"><b style="color:#144069">EASTERN INTERNATIONAL UNIVERSITY</b><h3 style="margin:12px 0">BÁO CÁO PHỎNG VẤN TUYỂN DỤNG</h3><div class="small">${candidate(a.candidateId).name} — ${a.position}</div></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0">${r.participants.map((uid,i)=>{const u=state.users[uid],rep=state.reports[r.id]?.[uid]||{};return `<div style="margin:16px 0"><b>Cán bộ phỏng vấn ${i+1}: ${u.name}</b><div class="small muted">Chức vụ: ${u.title}</div><div class="report-grid" style="margin-top:10px"><div class="label">Kiến thức chuyên môn</div><div>${rep.knowledge||'________________________________'}</div><div class="label">Kỹ năng cần thiết</div><div>${rep.skills||'________________________________'}</div><div class="label">Phẩm chất/tính cách</div><div>${rep.qualities||'________________________________'}</div><div class="label">Điểm mạnh và hạn chế</div><div>${rep.strengths||'________________________________'}</div><div class="label">Khác</div><div>${rep.other||'________________________________'}</div></div></div>`}).join('')}<hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><b>Kết luận hiện hành</b><div class="report-grid" style="margin-top:10px"><div class="label">Kết luận</div><div>${src?.[1]?.conclusion||'________________________________'}</div><div class="label">Dự kiến công việc</div><div>${src?.[1]?.job||'________________________________'}</div><div class="label">Thời gian dự kiến tuyển dụng</div><div>${src?.[1]?.time||'________________________________'}</div></div></div>`,`<button class="btn" onclick="closeModal()">Đóng</button><button class="btn primary">${icon('download')} Tải PDF</button>`)}

render();
