/* Responsive Prototype v1.9 — External Review v10 cross-layer identity/eligibility alignment. */
function submissionByIdV19(id){for(const c of state.candidates){const s=(c.submissions||[]).find(x=>x.id===id);if(s)return {candidate:c,submission:s};}return null;}
function submissionOptionTextV19(c,s){return `${c.name} — ${c.email} — Submitted: ${s.date} — Status: ${statusLabel[s.status]||s.status}`;}
function exactSubmissionOptionsV19(){return state.candidates.flatMap(c=>(c.submissions||[]).map(s=>`<option value="${s.id}">${submissionOptionTextV19(c,s)}</option>`)).join('');}
assignApplicationModal=function(){return modalFrame(tx('Ứng tuyển / Cập nhật Application','Assign / Update Application'),`<div class="form-grid"><div class="field wide"><label>${tx('Submission cụ thể','Exact Submission')} *</label><select id="applicationSubmissionV19" class="select" aria-label="Exact SubmissionSelector">${exactSubmissionOptionsV19()}</select><div class="small">${tx('Mỗi Submission của cùng một Candidate là một lựa chọn riêng. Backend không tự đoán latest Submission.','Each Submission is a distinct choice. Backend never guesses the latest Submission.')}</div></div><div class="field"><label>Khoa/Phòng *</label><select id="applicationUnitV19" class="select"><option>Khoa Kỹ thuật</option><option>Khoa Kinh tế</option></select></div><div class="field"><label>Ngành/Tổ</label><select id="applicationTeamV19" class="select"><option>Điện tử – Viễn thông</option></select></div><div class="field"><label>Vị trí *</label><select id="applicationPositionV19" class="select"><option>Giảng viên Điện tử – Viễn thông</option></select></div><div class="field"><label>HR phụ trách *</label><select id="applicationHrV19" class="select"><option>Nguyễn Thị An</option></select></div></div><div class="alert">${tx('Durable identity = Submission + Khoa/Phòng + Ngành/Tổ + Vị trí. Nếu đúng tổ hợp đã tồn tại, cập nhật/reactivate đúng Application đó.','Durable identity = Submission + Unit + Team + Position. An exact duplicate updates/reactivates that same Application.')}</div>`,`<button class="btn" onclick="closeModal()">${tx('Hủy','Cancel')}</button><button class="btn primary" onclick="saveApplicationAssignmentV19()">${tx('Lưu','Save')}</button>`)};
function saveApplicationAssignmentV19(){const submissionId=$('#applicationSubmissionV19').value,ref=submissionByIdV19(submissionId);if(!ref){toast('SUBMISSION_NOT_FOUND');return;}const unit=$('#applicationUnitV19').value,team=$('#applicationTeamV19').value,position=$('#applicationPositionV19').value,hr=$('#applicationHrV19').value;let a=state.applications.find(x=>x.submissionId===submissionId&&x.unit===unit&&x.team===team&&x.position===position);if(a){a.active=true;a.hr=hr;}else{a={id:'aProto-'+submissionId,submissionId,candidateId:ref.candidate.id,unit,team,position,hr,status:'AWAITING_INTERVIEW',active:true,rounds:[{id:'rProto-'+submissionId,no:1,topic:'',date:'',start:'',end:'',format:'',location:'',status:'AVAILABLE',note:'',participants:[],active:true}]};state.applications.push(a);}state.lastApplicationAssignmentV19={applicationId:a.id,submissionId,candidateId:ref.candidate.id};closeModal();toast(tx('Đã cập nhật Application theo exact Submission','Application updated from exact Submission'));render();}
function participantComboOptionV19(parts,label){return `<option value="${parts.join(',')}">${label}</option>`;}
roundModal=function(m){
 let sourceApp=appById(m.data?.appId||state.expandedApplication||'a1'),src=m.data?.roundId?roundById(m.data.roundId):currentRound(sourceApp),copy=m.type==='copyRound',edit=m.type==='editRound';
 const no=edit?src.no:Math.max(0,...sourceApp.rounds.map(r=>r.no))+1,dateVal=copy?isoDateV18(src?.date):edit?isoDateV18(src?.date):'2025-06-15'; const conflictContext=`${m.type}:${m.data?.appId||''}:${m.data?.roundId||''}`; if(state.roundConflictContextV19!==conflictContext){state.roundConflictContextV19=conflictContext;state.roundConflictV19='';}
 const srcParts=(copy||edit)?(src?.participants||[]):[]; const combos=[]; if(srcParts.length)combos.push([srcParts,srcParts.map(u=>state.users[u]?.name||u).join('; ')]); combos.push([['u1','u2','u3'],'TS. Trần Minh Khoa; ThS. Lê Hoàng Nam; ThS. Phạm Quỳnh Anh']);combos.push([['u1','u4'],'TS. Trần Minh Khoa; ThS. Trần Thu Hương']); const seen=new Set(); const opts=combos.filter(([ps])=>{const k=ps.join(',');if(seen.has(k))return false;seen.add(k);return true;}).map(([ps,l],i)=>`<option value="${ps.join(',')}" ${srcParts.join(',')===ps.join(',')?'selected':''}>${l}</option>`).join('');
 return modalFrame(copy?tx('Sao chép lịch phỏng vấn','Copy interview'):edit?tx('Chỉnh sửa lịch phỏng vấn','Edit interview'):tx('Tạo lịch phỏng vấn','Create interview'),`<div class="form-grid"><div class="field wide"><label>Application</label><select id="roundApp" class="select"><option value="${sourceApp.id}">${candidate(sourceApp.candidateId).name} — ${sourceApp.position}</option>${state.applications.filter(x=>x.id!==sourceApp.id).map(x=>`<option value="${x.id}">${candidate(x.candidateId).name} — ${x.position}</option>`).join('')}</select></div><div class="field"><label>${tx('Vòng','Round')}</label><input id="roundNo" class="input" value="${no}" disabled></div><div class="field"><label>Demo Topic</label><input id="roundTopic" class="input" value="${copy?'':src?.topic||''}" placeholder="${tx('Vòng mới để trống','New round stays blank')}"></div><div class="field"><label>${tx('Ngày','Date')} *</label><input id="roundDate" class="input" type="date" value="${dateVal}"></div><div class="field"><label>${tx('Giờ bắt đầu','Start time')} *</label><input id="roundStart" class="input" type="time" value="${copy||edit?src?.start||'09:00':'09:00'}"></div><div class="field"><label>${tx('Giờ kết thúc','End time')} *</label><input id="roundEnd" class="input" type="time" value="${copy||edit?src?.end||'10:00':'10:00'}"></div><div class="field"><label>${tx('Hình thức','Format')}</label><select id="roundFormat" class="select"><option ${src?.format==='Trực tiếp'?'selected':''}>Trực tiếp</option><option ${src?.format==='Online'?'selected':''}>Online</option></select></div><div class="field"><label>${tx('Địa điểm','Location')}</label><input id="roundLocation" class="input" value="${copy||edit?src?.location||'':'Phòng 11.101.B5'}"></div><div class="field wide"><label>${tx('Người tham dự','Participants')}</label><select id="roundParticipants" class="select">${opts}</select></div></div><div id="conflictBox">${state.roundConflictV19?`<div class="alert">${state.roundConflictV19}</div>`:''}</div>`,`<button class="btn" onclick="closeModal()">${tx('Hủy','Cancel')}</button><button class="btn primary" onclick="saveRound('${m.type}','${src?.id||''}')">${tx('Xác nhận','Confirm')}</button>`);
};
const _saveRoundV18V19=saveRound;
saveRound=function(type,srcId){const parts=($('#roundParticipants')?.value||'').split(',').filter(Boolean),inactive=parts.filter(uid=>!state.users[uid]||state.users[uid].active===false);state.roundConflictV19='';if(inactive.length){state.roundConflictV19=`CURRENT_PARTICIPANT_INACTIVE_REASSIGN_REQUIRED: ${inactive.map(u=>state.users[u]?.name||u).join(', ')}`;const box=$('#conflictBox');if(box)box.innerHTML=`<div class="alert">${state.roundConflictV19}</div>`;return;}_saveRoundV18V19(type,srcId);const box=$('#conflictBox');if(box&&box.innerText.trim())state.roundConflictV19=box.innerText.trim();};
const _shellV19=shell;shell=function(content,title,sub=''){return _shellV19(content,title,sub).replace(/Responsive UX-UAT v1\.8/g,'Responsive UX-UAT v1.9');};
const _loginPageV19=loginPage;loginPage=function(){return _loginPageV19().replace(/Responsive UX-UAT v1\.8/g,'Responsive UX-UAT v1.9');};
render();
